spring:
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      # Acknowledgment level:
      # "0": Producer does not wait for any acknowledgment from the broker (highest throughput, lowest durability).
      # "1": Producer waits for only the leader broker to acknowledge (balance between throughput and durability).
      # "all" (or "-1"): Producer waits for all in-sync replicas to acknowledge (lowest throughput, highest durability/guarantee of no message loss).
      acks: 0 # Recommended for high reliability
      # Other useful properties for reliability:
      retries: 3 # Number of times to retry a failed send
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: xpayment-adapter-result-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.radmiy.payment.service.api.dto.XPaymentAdapterResponseMessage"
    listener:
      ack-mode: manual
      concurrency: 1

app:
  kafka:
    topics:
      xpayment-adapter:
        request-topic: xpayment-adapter.requests
        response-topic: xpayment-adapter.responses