apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-payment-adapter-app
  labels:
    app: x-payment-adapter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: x-payment-adapter-app
  template:
    metadata:
      labels:
        app: x-payment-adapter-app
    spec:
      containers:
        - name: x-payment-adapter-app
          image: x-payment-adapter-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: mgmt
              containerPort: 8081
          startupProbe:
            httpGet:
              port: mgmt
              path: /actuator/health/liveness
            periodSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              port: mgmt
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: mgmt
              path: /actuator/health/readiness
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "xpayment-adapter-result-consumers"
            - name: APP_KAFKA_TOPIC_REQUEST
              value: "xpayment-adapter.requests"
            - name: APP_KAFKA_TOPIC_RESPONSE
              value: "xpayment-adapter.responses"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq.rabbit.svc.cluster.local:5672"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq.rabbit.svc.cluster.local"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin.observability.svc.cluster.local:9411/api/v2/spans

---
apiVersion: v1
kind: Service
metadata:
  name: x-payment-adapter-app
spec:
  selector:
    app: x-payment-adapter-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP