spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        observation-enabled: true
    template:
      observation-enabled: true
app:
  rabbitmq:
    exchange-name: payment-state-check-exchange
    queue-name: payment-state-check-queue
    max-retries: 60
    interval-ms: 30000
