version: '3.8'

services:
  payment-service-app:
    image: payment-service-app
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: payment-db
      LC_MESSAGES: en_US.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
volumes:
  pgdata:
